export const CRYPTO_COLUMNS: string[] = [
  "close",
  "change",
  "change_abs",
  "volume",
  "market_cap_calc",
  "Recommend.All",
  "Recommend.MA",
  "Recommend.Other",
  "RSI",
  "MACD.macd",
  "MACD.signal",
  "Stoch.K",
  "Stoch.D",
  "BB.lower",
  "BB.upper",
  "EMA20",
  "EMA50",
  "EMA200",
  "SMA20",
  "SMA50",
  "SMA200",
  "description",
  "name",
];

export const CRYPTO_TIMEFRAMES: Record<string, string> = {
  "1m": "|1",
  "5m": "|5",
  "15m": "|15",
  "1h": "|60",
  "4h": "|240",
  "1W": "|1W",
  "1M": "|1M",
  "1d": "",
};
