export const STOCK_COLUMNS: string[] = [
  "close",
  "change",
  "change_abs",
  "volume",
  "market_cap_basic",
  "price_earnings_ttm",
  "earnings_per_share_basic_ttm",
  "number_of_employees",
  "sector",
  "description",
  "name",
  "type",
  "subtype",
  "update_mode",
  "exchange",
  "currency_code",
  "pricescale",
  "minmov",
  "fractional",
  "minmove2",
  "Recommend.All",
  "Recommend.MA",
  "Recommend.Other",
  "RSI",
  "RSI[1]",
  "Stoch.K",
  "Stoch.D",
  "Stoch.K[1]",
  "Stoch.D[1]",
  "CCI20",
  "CCI20[1]",
  "ADX",
  "ADX+DI",
  "ADX-DI",
  "ADX+DI[1]",
  "ADX-DI[1]",
  "AO",
  "AO[1]",
  "AO[2]",
  "Mom",
  "Mom[1]",
  "MACD.macd",
  "MACD.signal",
  "BB.lower",
  "BB.upper",
  "Pivot.M.Classic.S3",
  "Pivot.M.Classic.S2",
  "Pivot.M.Classic.S1",
  "Pivot.M.Classic.Middle",
  "Pivot.M.Classic.R1",
  "Pivot.M.Classic.R2",
  "Pivot.M.Classic.R3",
  "EMA5",
  "EMA10",
  "EMA20",
  "EMA30",
  "EMA50",
  "EMA100",
  "EMA200",
  "SMA5",
  "SMA10",
  "SMA20",
  "SMA30",
  "SMA50",
  "SMA100",
  "SMA200",
];

export const STOCK_TIMEFRAMES: Record<string, string> = {
  "1m": "|1",
  "5m": "|5",
  "15m": "|15",
  "1h": "|60",
  "4h": "|240",
  "1W": "|1W",
  "1M": "|1M",
  "1d": "",  // daily is default, no suffix
};
